### ISSUE TITLE
Readme suggestion for htm.core

### ISSUE THREAD

**Issue by breznak** [Zbysekz/HTMpandaVis#1]
Hi @Zbysekz , this looks really awesome! :+1: Congratulations! 
And thanks for bringing the project under the htm-community umbrella. 

A few suggestions as I'm going to test this proj: 
- you could put the requirements (along with the minimal supported versions) to a `requirements.txt` file for easier install 
- would you like to make a PR to htm.core Readme with a section 
```
##Related community work

Community projects for working with HTM. 

### Visualization
#### HTMPandaVis

and put your short description and a nice image here
```
?

**Comment by breznak** [comment]
I was reading the example `hotgym.py` in here, could you please explain better something like "Visualizing your HTM code"? 

- what data needs to be fed (and how structured)
- which code needs be called (and possibly minimize/wrap that?)

**Comment by Zbysekz** [comment]
Hello @breznak,
Ok, i will vreate the requirements and put the readme description.

It is on my TODO list to make section in README sort describing how to implement pandaVis
but basically:
- copy paste pandaComm folder into your directory
- copy&paste python imports
- create server global variable 'pandaServer = PandaServer()' and run it at init
- modify BuildPandaSystem() to fit your architecture
- feed in loop your architecture structure, what you will fill you will see in vis when requested
- you can block loop by adding condition as in example to be able to debug individual steps

**Comment by Zbysekz** [comment]
About the structure of data that are communicated:
[https://github.com/htm-community/HTMpandaVis/blob/master/HotgymExample/pandaComm/dataExchange.py](url)

**Comment by Zbysekz** [comment]
Readme was updated
