### ISSUE TITLE
Traceback (most recent call last):   File "hotgym.py", line 340, in <module>     main()   File "hotgym.py", line 216, in main     pdf = predictor.infer(count, tm.getActiveCells()) TypeError: infer(): incompatible function arguments. The following argument types are supported:     1. (self: htm.bindings.algorithms.Predictor, pattern: htm.bindings.sdr.SDR) -> Dict[int, List[float]]  Invoked with: <htm.bindings.algorithms.Predictor object at 0x7f2eabb52e30>, 0, <htm.bindings.sdr.SDR object at 0x7f2eabb52ea0>

### ISSUE THREAD

**Issue by ycttq** [Zbysekz/HTMpandaVis#2]
Hi , one problem on run application.my environment is ubuntu18 and Annaconda ,i try run it ,but has problem. please help .Thanks
`Traceback (most recent call last):
  File "hotgym.py", line 340, in <module>
    main()
  File "hotgym.py", line 216, in main
    pdf = predictor.infer(count, tm.getActiveCells())
TypeError: infer(): incompatible function arguments. The following argument types are supported:
    1. (self: htm.bindings.algorithms.Predictor, pattern: htm.bindings.sdr.SDR) -> Dict[int, List[float]]

Invoked with: <htm.bindings.algorithms.Predictor object at 0x7f2eabb52e30>, 0, <htm.bindings.sdr.SDR object at 0x7f2eabb52ea0>
`

**Comment by Zbysekz** [comment]
Hello @ycttq, Thanks for reporting.
It seems that the Predictor interface was changed, by commit df7ae4ed5fd920b4d82801059dfa511211a6aca4 made by @breznak. (No offense, just pointing out :) )
I think that maybe the only change is that "count" variable is now not necessary.
Try change `pdf = predictor.infer(tm.getActiveCells())`

Anyway i will make an update of the hotgym example to be aligned with latest htm.core version.

**Comment by ycttq** [comment]
@Zbysekz yeah, I just  follow it,it's work very well ,thanks

**Comment by Zbysekz** [comment]
@ycttq Now this update is in the repo. There was also one other issue: the anomaly score was not calculated properly (returned always -1, in the anomaly plot after script finished was flat line). It was due to updates
